"""empty message

Revision ID: 180ec1bd526d
Revises: b4597ad1b30
Create Date: 2015-01-11 20:20:37.347359

"""

# revision identifiers, used by Alembic.
revision = '180ec1bd526d'
down_revision = 'b4597ad1b30'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('crawl', sa.Column('harvest_rate', sa.Float(), nullable=True))
    op.add_column('crawl', sa.Column('pages_crawled', sa.BigInteger(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('crawl', 'pages_crawled')
    op.drop_column('crawl', 'harvest_rate')
    ### end Alembic commands ###
