"""empty message

Revision ID: 19e28e1e2ce8
Revises: 87fce75f43
Create Date: 2015-01-06 16:15:06.631412

"""

# revision identifiers, used by Alembic.
revision = '19e28e1e2ce8'
down_revision = '87fce75f43'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('image', sa.Column('img_dir', sa.String(length=140), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('image', 'img_dir')
    ### end Alembic commands ###
