"""empty message

Revision ID: 1f0328fe4fd5
Revises: 507f8b484280
Create Date: 2014-12-17 02:35:19.752293

"""

# revision identifiers, used by Alembic.
revision = '1f0328fe4fd5'
down_revision = '507f8b484280'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('dashboard', sa.Column('url', sa.String(length=140), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('dashboard', 'url')
    ### end Alembic commands ###
