"""empty message

Revision ID: 3b79c7975f42
Revises: None
Create Date: 2014-12-04 17:58:05.289547

"""

# revision identifiers, used by Alembic.
revision = '3b79c7975f42'
down_revision = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('data_model',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('project',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('icon', sa.String(length=64), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('team',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=True),
    sa.Column('leader_id', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=64), nullable=True),
    sa.Column('password', sa.String(length=12), nullable=True),
    sa.Column('email', sa.String(length=50), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('username')
    )
    op.create_table('image',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('img_file', sa.String(length=140), nullable=True),
    sa.Column('EXIF_LensSerialNumber', sa.String(length=140), nullable=True),
    sa.Column('MakerNote_SerialNumberFormat', sa.String(length=140), nullable=True),
    sa.Column('EXIF_BodySerialNumber', sa.String(length=140), nullable=True),
    sa.Column('MakerNote_InternalSerialNumber', sa.String(length=140), nullable=True),
    sa.Column('MakerNote_SerialNumber', sa.String(length=140), nullable=True),
    sa.Column('Image_BodySerialNumber', sa.String(length=140), nullable=True),
    sa.Column('Uploaded', sa.Integer(), nullable=True),
    sa.Column('project_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['project_id'], ['project.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('crawl',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('crawler', sa.Text(), nullable=True),
    sa.Column('config', sa.Text(), nullable=True),
    sa.Column('project_id', sa.Integer(), nullable=True),
    sa.Column('data_model_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['data_model_id'], ['data_model.id'], ),
    sa.ForeignKeyConstraint(['project_id'], ['project.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('team_user',
    sa.Column('team_id', sa.Integer(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['team_id'], ['team.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], )
    )
    op.create_table('dashboard',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('project_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['project_id'], ['project.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('image_space',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('images_location', sa.Text(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('project_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['project_id'], ['project.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('data_source',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=True),
    sa.Column('data_uri', sa.String(length=120), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('project_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['project_id'], ['project.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('plot',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('endpoint', sa.String(length=64), nullable=True),
    sa.Column('plot', sa.String(length=64), nullable=True),
    sa.Column('project_id', sa.Integer(), nullable=True),
    sa.Column('source_id', sa.String(length=64), nullable=True),
    sa.Column('autoload_tag', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['project_id'], ['project.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_plot_endpoint'), 'plot', ['endpoint'], unique=True)
    op.create_index(op.f('ix_plot_plot'), 'plot', ['plot'], unique=False)
    op.create_table('crawl_images',
    sa.Column('crawl_id', sa.Integer(), nullable=True),
    sa.Column('image_space_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['crawl_id'], ['crawl.id'], ),
    sa.ForeignKeyConstraint(['image_space_id'], ['image_space.id'], )
    )
    op.create_table('data_plot',
    sa.Column('data_source_id', sa.Integer(), nullable=True),
    sa.Column('plot_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['data_source_id'], ['data_source.id'], ),
    sa.ForeignKeyConstraint(['plot_id'], ['plot.id'], )
    )
    op.create_table('crawl_data',
    sa.Column('crawl_id', sa.Integer(), nullable=True),
    sa.Column('data_source_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['crawl_id'], ['crawl.id'], ),
    sa.ForeignKeyConstraint(['data_source_id'], ['data_source.id'], )
    )
    op.create_table('plot_dashboard',
    sa.Column('plot_id', sa.Integer(), nullable=True),
    sa.Column('dashboard_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['dashboard_id'], ['dashboard.id'], ),
    sa.ForeignKeyConstraint(['plot_id'], ['plot.id'], )
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('plot_dashboard')
    op.drop_table('crawl_data')
    op.drop_table('data_plot')
    op.drop_table('crawl_images')
    op.drop_index(op.f('ix_plot_plot'), table_name='plot')
    op.drop_index(op.f('ix_plot_endpoint'), table_name='plot')
    op.drop_table('plot')
    op.drop_table('data_source')
    op.drop_table('image_space')
    op.drop_table('dashboard')
    op.drop_table('team_user')
    op.drop_table('crawl')
    op.drop_table('image')
    op.drop_table('user')
    op.drop_table('team')
    op.drop_table('project')
    op.drop_table('data_model')
    ### end Alembic commands ###
