"""empty message

Revision ID: 476dacbdf758
Revises: 2f00bc6c99cd
Create Date: 2014-11-25 15:22:31.674681

"""

# revision identifiers, used by Alembic.
revision = '476dacbdf758'
down_revision = '2f00bc6c99cd'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
