"""empty message

Revision ID: 507f8b484280
Revises: 7811152744c
Create Date: 2014-12-16 15:23:31.618601

"""

# revision identifiers, used by Alembic.
revision = '507f8b484280'
down_revision = '7811152744c'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('image_space', sa.Column('name', sa.String(length=64), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('image_space', 'name')
    ### end Alembic commands ###
