"""empty message

Revision ID: 620ff718add
Revises: 1f0328fe4fd5
Create Date: 2014-12-22 17:04:45.691216

"""

# revision identifiers, used by Alembic.
revision = '620ff718add'
down_revision = '1f0328fe4fd5'

from alembic import op
import sqlalchemy as sa
from webhelpers import text

connection = op.get_bind()

crawl_helper = sa.Table(
    'crawl',
    sa.MetaData(),
    sa.Column('id', sa.Integer, primary_key=True),
    sa.Column('name', sa.String(64)),
    sa.Column('slug', sa.String(64), unique=True),
)

imagespace_helper = sa.Table(
    'image_space',
    sa.MetaData(),
    sa.Column('id', sa.Integer, primary_key=True),
    sa.Column('name', sa.String(64)),
    sa.Column('slug', sa.String(64), unique=True),
)

project_helper = sa.Table(
    'project',
    sa.MetaData(),
    sa.Column('id', sa.Integer, primary_key=True),
    sa.Column('name', sa.String(64)),
    sa.Column('slug', sa.String(64), unique=True),
)


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('crawl', sa.Column('slug', sa.String(length=64), nullable=True))
    op.add_column('image_space', sa.Column('slug', sa.String(length=64), nullable=True))
    op.add_column('project', sa.Column('slug', sa.String(length=64), nullable=True))

    for crawl in connection.execute(crawl_helper.select()):
        crawl_name = crawl.name
        connection.execute(
            crawl_helper.update().where(
                crawl_helper.c.id == crawl.id
            ).values(
                slug = text.urlify(crawl_name)
            )
        )

    for image_space in connection.execute(imagespace_helper.select()):
        image_space_name = image_space.name
        connection.execute(
            imagespace_helper.update().where(
                imagespace_helper.c.id == image_space.id
            ).values(
                slug = text.urlify(image_space_name)
            )
        )

    for project in connection.execute(project_helper.select()):
        project_name = project.name
        connection.execute(
            project_helper.update().where(
                project_helper.c.id == project.id
            ).values(
                slug = text.urlify(project_name)
            )
        )

    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('project', 'slug')
    op.drop_column('image_space', 'slug')
    op.drop_column('crawl', 'slug')
    ### end Alembic commands ###
