"""empty message

Revision ID: 7811152744c
Revises: 2b86638027d3
Create Date: 2014-12-16 12:23:11.462681

"""

# revision identifiers, used by Alembic.
revision = '7811152744c'
down_revision = '2b86638027d3'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('image_image',
    sa.Column('source_image_id', sa.Integer(), nullable=True),
    sa.Column('match_image_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['match_image_id'], ['image.id'], ),
    sa.ForeignKeyConstraint(['source_image_id'], ['image.id'], )
    )
    op.create_table('crawl_image',
    sa.Column('crawl_id', sa.Integer(), nullable=True),
    sa.Column('image_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['crawl_id'], ['crawl.id'], ),
    sa.ForeignKeyConstraint(['image_id'], ['image.id'], )
    )
    op.drop_table('crawl_images')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('crawl_images',
    sa.Column('crawl_id', sa.INTEGER(), nullable=True),
    sa.Column('image_space_id', sa.INTEGER(), nullable=True),
    sa.ForeignKeyConstraint(['crawl_id'], [u'crawl.id'], ),
    sa.ForeignKeyConstraint(['image_space_id'], [u'image_space.id'], )
    )
    op.drop_table('crawl_image')
    op.drop_table('image_image')
    ### end Alembic commands ###
