"""empty message

Revision ID: 87fce75f43
Revises: 620ff718add
Create Date: 2014-12-29 17:42:02.539577

"""

# revision identifiers, used by Alembic.
revision = '87fce75f43'
down_revision = '620ff718add'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('image_image_space',
    sa.Column('image_space_id', sa.Integer(), nullable=True),
    sa.Column('image_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['image_id'], ['image.id'], ),
    sa.ForeignKeyConstraint(['image_space_id'], ['image_space.id'], )
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('image_image_space')
    ### end Alembic commands ###
