"""empty message

Revision ID: b4597ad1b30
Revises: None
Create Date: 2015-01-09 14:03:19.690988

"""

# revision identifiers, used by Alembic.
revision = 'b4597ad1b30'
down_revision = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('project',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=True),
    sa.Column('slug', sa.String(length=64), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('icon', sa.String(length=64), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name'),
    sa.UniqueConstraint('slug')
    )
    op.create_table('data_model',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.Text(), nullable=True),
    sa.Column('project_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['project_id'], ['project.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('crawl',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=True),
    sa.Column('slug', sa.String(length=64), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('crawler', sa.String(length=64), nullable=True),
    sa.Column('status', sa.String(length=64), nullable=True),
    sa.Column('config', sa.String(length=64), nullable=True),
    sa.Column('seeds_list', sa.String(length=64), nullable=True),
    sa.Column('project_id', sa.Integer(), nullable=True),
    sa.Column('data_model_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['data_model_id'], ['data_model.id'], ),
    sa.ForeignKeyConstraint(['project_id'], ['project.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name'),
    sa.UniqueConstraint('slug')
    )
    op.create_table('data_source',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=True),
    sa.Column('data_uri', sa.String(length=120), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('project_id', sa.Integer(), nullable=True),
    sa.Column('crawl_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['crawl_id'], ['crawl.id'], ),
    sa.ForeignKeyConstraint(['project_id'], ['project.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('image_space',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=True),
    sa.Column('slug', sa.String(length=64), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('project_id', sa.Integer(), nullable=True),
    sa.Column('crawl_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['crawl_id'], ['crawl.id'], ),
    sa.ForeignKeyConstraint(['project_id'], ['project.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name'),
    sa.UniqueConstraint('slug')
    )
    op.create_table('plot',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('endpoint', sa.String(length=64), nullable=True),
    sa.Column('plot', sa.String(length=64), nullable=True),
    sa.Column('project_id', sa.Integer(), nullable=True),
    sa.Column('crawl_id', sa.Integer(), nullable=True),
    sa.Column('source_id', sa.String(length=64), nullable=True),
    sa.Column('autoload_tag', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['crawl_id'], ['crawl.id'], ),
    sa.ForeignKeyConstraint(['project_id'], ['project.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_plot_endpoint'), 'plot', ['endpoint'], unique=True)
    op.create_index(op.f('ix_plot_plot'), 'plot', ['plot'], unique=False)
    op.create_table('data_plot',
    sa.Column('data_source_id', sa.Integer(), nullable=True),
    sa.Column('plot_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['data_source_id'], ['data_source.id'], ),
    sa.ForeignKeyConstraint(['plot_id'], ['plot.id'], )
    )
    op.create_table('image',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('filename', sa.String(length=140), nullable=True),
    sa.Column('EXIF_LensSerialNumber', sa.String(length=140), nullable=True),
    sa.Column('MakerNote_SerialNumberFormat', sa.String(length=140), nullable=True),
    sa.Column('EXIF_BodySerialNumber', sa.String(length=140), nullable=True),
    sa.Column('MakerNote_InternalSerialNumber', sa.String(length=140), nullable=True),
    sa.Column('MakerNote_SerialNumber', sa.String(length=140), nullable=True),
    sa.Column('Image_BodySerialNumber', sa.String(length=140), nullable=True),
    sa.Column('uploaded', sa.Integer(), nullable=True),
    sa.Column('image_space_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['image_space_id'], ['image_space.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('image')
    op.drop_table('data_plot')
    op.drop_index(op.f('ix_plot_plot'), table_name='plot')
    op.drop_index(op.f('ix_plot_endpoint'), table_name='plot')
    op.drop_table('plot')
    op.drop_table('image_space')
    op.drop_table('data_source')
    op.drop_table('crawl')
    op.drop_table('data_model')
    op.drop_table('project')
    ### end Alembic commands ###
