package:
  name: cherrypy
  version: "3.8.0"

source:
  fn: CherryPy-3.8.0.tar.gz
  url: https://pypi.python.org/packages/source/C/CherryPy/CherryPy-3.8.0.tar.gz
  md5: 542b96b2cd825e8120e8cd822bc18f4b
#  patches:
   # List any patch files here
   # - fix.patch

# build:
  # noarch_python: True
  # preserve_egg_dir: True
  # entry_points:
    # Put any entry points (scripts to be generated automatically) here. The
    # syntax is module:function.  For example
    #
    # - cherrypy = cherrypy:main
    #
    # Would create an entry point called cherrypy that calls cherrypy.main()


  # If this is a new build for the same version, increment the build
  # number. If you do not include this key, it defaults to 0.
  # number: 1

requirements:
  build:
    - python
    - setuptools

  run:
    - python

test:
  # Python imports
  imports:
    - cherrypy
    - cherrypy.lib
    - cherrypy.process
    - cherrypy.scaffold
    - cherrypy.test
    - cherrypy.tutorial
    - cherrypy.wsgiserver

  # commands:
    # You can put test commands to be run here.  Use this to test that the
    # entry points work.


  # You can also put a file called run_test.py in the recipe that will be run
  # at test time.

  # requires:
    # Put any additional test requirements here.  For example
    # - nose

about:
  home: http://www.cherrypy.org
  license: BSD License
  summary: 'Object-Oriented HTTP framework'

# See
# http://docs.continuum.io/conda/build.html for
# more information about meta.yaml
